{
 "title": "POC-Rastreabilidade",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Total acessos Login",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "login_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total acessos Home",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "home_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total requests http",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "http_responses_total", "legendFormat": "__auto" }
   ]
  }
 ]
}